# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work

os:
  - linux
  - osx

env:
  - BUILD=stack ARGS="--resolver nightly"  # stack nightly
  - BUILD=stack ARGS=""  # stack default
  - BUILD=stack ARGS="--resolver lts-18.21"  # stack 8.10.7
  - BUILD=stack ARGS="--resolver lts-18.8"  # stack 8.10.6
  - BUILD=stack ARGS="--resolver lts-18.6"  # stack 8.10.4
  - BUILD=stack ARGS="--resolver lts-17.2"  # stack 8.10.3
  - BUILD=stack ARGS="--resolver lts-16.31"  # stack 8.8.4
  - BUILD=stack ARGS="--resolver lts-16.11"  # stack 8.8.3
  - BUILD=stack ARGS="--resolver lts-15.3"  # stack 8.8.2
  # - BUILD=stack ARGS="--resolver lts-14.27"  # stack 8.6.5
  # - BUILD=stack ARGS="--resolver lts-13.19"  # stack 8.6.4
  # - BUILD=stack ARGS="--resolver lts-13.11"  # stack 8.6.3
  # - BUILD=stack ARGS="--resolver lts-12.26"  # stack 8.4.4
  # - BUILD=stack ARGS="--resolver lts-12.14"  # stack 8.4.3
  # - BUILD=stack ARGS="--resolver lts-11.22"  # stack 8.2.2
  # - BUILD=stack ARGS="--resolver lts-9.21"  # stack 8.0.2
  # - BUILD=stack ARGS="--resolver lts-7.24"  # stack 8.0.1
  # - BUILD=stack ARGS="--resolver lts-6.35"  # stack 7.10.3
  # - BUILD=stack ARGS="--resolver lts-3.22"  # stack 7.10.2
  # - BUILD=stack ARGS="--resolver lts-2.22"  # stack 7.8.4
  # - BUILD=stack ARGS="--resolver lts-0.7"  # stack 7.8.3

# Nightly builds are allowed to fail
jobs:
  allow_failures:
    - env: BUILD=stack ARGS="--resolver nightly"

before_install:
  # Download and unpack the stack executable
  - export PATH=$HOME/.local/bin:$HOME/.cabal/bin:$PATH
  - mkdir -p ~/.local/bin
  - |
    if [ `uname` = "Darwin" ]
    then
      travis_retry curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi

install:
  - stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script:
  - stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
