# Run jobs on Linux unless "os" is specified explicitly.
os: linux

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
jobs:
  include:
  # Build on Linux
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS=""
    compiler: ": #stack default"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-16.23"
    compiler: ": #stack 8.8.4"
    addons: {apt: {packages: [libgmp-dev]}}
  
  - env: BUILD=stack ARGS="--resolver lts-16.11"
    compiler: ": #stack 8.8.3"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-15.3"
    compiler: ": #stack 8.8.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-14.27"
    compiler: ": #stack 8.6.5"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-13.19"
    compiler: ": #stack 8.6.4"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-13.11"
    compiler: ": #stack 8.6.3"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-12.26"
    compiler: ": #stack 8.4.4"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-12.14"
    compiler: ": #stack 8.4.3"
    addons: {apt: {packages: [libgmp-dev]}}
    
  - env: BUILD=stack ARGS="--resolver lts-11.22"
    compiler: ": #stack 8.2.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-9.21"
    compiler: ": #stack 8.0.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-7.24"
    compiler: ": #stack 8.0.1"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-6.35"
    compiler: ": #stack 7.10.3"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-3.22"
    compiler: ": #stack 7.10.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-2.22"
    compiler: ": #stack 7.8.4"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stack ARGS="--resolver lts-0.7"
    compiler: ": #stack 7.8.3"
    addons: {apt: {packages: [libgmp-dev]}}

  # Build on macOS
  - env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    os: osx

  - env: BUILD=stack ARGS=""
    compiler: ": #stack default"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-16.23"
    compiler: ": #stack 8.8.4"
    os: osx
  
  - env: BUILD=stack ARGS="--resolver lts-16.11"
    compiler: ": #stack 8.8.3"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-15.3"
    compiler: ": #stack 8.8.2"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-14.27"
    compiler: ": #stack 8.6.5"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-13.19"
    compiler: ": #stack 8.6.4"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-13.11"
    compiler: ": #stack 8.6.3"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-12.26"
    compiler: ": #stack 8.4.4"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-12.14"
    compiler: ": #stack 8.4.3"
    os: osx
    
  - env: BUILD=stack ARGS="--resolver lts-11.22"
    compiler: ": #stack 8.2.2"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-9.21"
    compiler: ": #stack 8.0.2"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-7.24"
    compiler: ": #stack 8.0.1"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-6.35"
    compiler: ": #stack 7.10.3"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-3.22"
    compiler: ": #stack 7.10.2"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-2.22"
    compiler: ": #stack 7.8.4"
    os: osx

  - env: BUILD=stack ARGS="--resolver lts-0.7"
    compiler: ": #stack 7.8.3"
    os: osx

  # Nightly builds are allowed to fail
  allow_failures:
  - env: BUILD=stack ARGS="--resolver nightly"

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Download and unpack the stack executable
- export PATH=$HOME/.local/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

  # Use the more reliable S3 mirror of Hackage
  mkdir -p $HOME/.cabal
  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config


install:
- stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script:
- stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
