name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macOS-15, windows-2025]
        ghc:
          - "9.0.2"
          - "9.2.8"
          - "9.4.8"
          - "9.6.6"
          - "9.8.4"
          - "9.10.1"
          - "9.12.1"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Cabal and GHC
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Cache Linux/Mac
      uses: actions/cache@v4
      if: ${{ matrix.os != 'windows-latest' }}
      with:
        path: ~/.cabal
        key: -${{ runner.os }}-${{ matrix.ghc }}-build-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}-
        restore-keys: |
          -${{ runner.os }}-${{ matrix.ghc }}-build-
          -${{ runner.os }}-

    - name: Cache Windows
      uses: actions/cache@v4
      if: ${{ matrix.os == 'windows-latest' }}
      with:
        path: C:\sr\
        # path: ~/AppData/Roaming/cabal
        key: -${{ runner.os }}-${{ matrix.ghc }}-build-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}-
        restore-keys: |
          -${{ runner.os }}-${{ matrix.ghc }}-build-
          -${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: cabal test all

  stack:
    name: ${{ matrix.os }} / stack ${{ matrix.stack-resolver }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macOS-15, windows-2025]
        stack-resolver:
          - "--resolver nightly"  # stack nightly
          - ""  # stack default
          - "--resolver lts-22.6"  # ghc 9.6.3
          - "--resolver lts-21.25"  # ghc 9.4.8
          - "--resolver lts-21.21"  # ghc 9.4.7
          - "--resolver lts-21.11"  # ghc 9.4.6
          - "--resolver lts-21.7"  # ghc 9.4.5
          - "--resolver lts-20.26"  # ghc 9.2.8
          - "--resolver lts-20.24"  # ghc 9.2.7
          - "--resolver lts-20.12"  # ghc 8.2.6
          - "--resolver lts-20.11"  # ghc 9.2.5
          - "--resolver lts-19.33"  # stack 9.0.2
          - "--resolver lts-18.28"  # stack 8.10.7
        exclude:
          # Broken configuration for some reason
          - os: windows-2025
            stack-resolver: "--resolver nightly"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Haskell Stack
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true
        stack-no-global: true

    - name: Cache Linux/Mac
      uses: actions/cache@v4
      if: ${{ matrix.os != 'windows-latest' }}
      with:
        path: ~/.stack
        key: -${{ runner.os }}-${{ matrix.stack-resolver }}-

    - name: Cache Windows
      uses: actions/cache@v4
      if: ${{ matrix.os == 'windows-latest' }}
      with:
        path: C:\sr\
        # path: ~\AppData\Local\Programs\stack
        key: -${{ runner.os }}-${{ matrix.stack-resolver }}-

    - name: Setup
      run: |
        stack setup ${{ matrix.stack-resolver }}

    - name: Build
      run: |
        stack build ${{ matrix.stack-resolver }} --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test ${{ matrix.stack-resolver }}
